### PR TITLE
Add support for anonymous containers

### PR DESCRIPTION
**Pull request by white-gecko**
This does the same as #116 just for Containers.

- [x] Add test

### CODE REVIEW

**Comment by white-gecko** [comment]
This still needs a test for the new behavior. @Simaris can you please show me, how I can test this new feature?

**Comment by Simaris** [comment]
we can use the same test as for the same case for collections

**Comment by Simaris** [comment]
adding the following lines:
´´´ruby
  should "accept a resource predicate tupel as pointer (shortcut) to a collection" do
      answer = rdf_collection("<http://example.org/instance/conPointer>", "<http://example.org/instance/contain>")
      assert(answer.any? {|resource| resource.to_s.eql? "http://example.org/instance/conItem1"}, "answerset does not contain 'http://example.org/instance/conItem1'")
      assert(answer.any? {|resource| resource.to_s.eql? "http://example.org/instance/colntem2"}, "answerset does not contain 'http://example.org/instance/conItem2'")
      assert(answer.any? {|resource| resource.to_s.eql? "http://example.org/instance/conItem3"}, "answerset does not contain 'http://example.org/instance/conItem3'")
      assert(answer.any? {|resource| resource.to_s.eql? "http://example.org/instance/conItem4"}, "answerset does not contain 'http://example.org/instance/conItem4'")
      assert(answer.any? {|resource| resource.to_s.eql? "http://example.org/instance/conItem5"}, "answerset does not contain 'http://example.org/instance/conItem5'")
    end
´´´

**Comment by Simaris** [comment]
I added a MWE for testing.
It also contains an inactive test file, that becomes active when #201 is merged.

**Pull request merged**
