### PR TITLE
replace umlauts in uri file names

### LINKED ISSUE #65: Resources with Umlaut in the URI are rendered to rdfsites/blanknode/
Resources with Umlaut (üöä) in the URI are rendered to `…/rdfsites/blanknode/` but they should be rendered to the normal location.

E.g. `http://example.org/Sören` is rendered to `http://localhost:4000/rdfsites/blanknode/http_D/example.org/Sören/index.html`.
It should be `http://localhost:4000/Sören/index.html`

### PR DESCRIPTION
**Pull request by Simaris**
Fix #65

### CODE REVIEW

**Comment by Simaris** [comment]
that pullrequest is a workaround #65 
it does not solve the problem but replaces äöüß to corresponding ascii combinations

**Comment by white-gecko** [comment]
But replacing the umlauts is not the intended behavior. Is this problem caused by some underlaying function?

**Comment by Simaris** [comment]
The problematic function is URI::split(iri). It throws an Exception which causes the resource to be rendered in /rdfsites/invalids/

**Comment by Simaris** [comment]
I switched to another function that seems to work just fine with some adjustments to the code.

**Comment by white-gecko** [comment]
Cool, could you please squash the commits? then the pull request should be ready for merging.

**Pull request merged**
